config/routes.rb
Rails.application.routes.draw do
  resources :stock_moves
  get '/stock_moves/kardex/:product_id', to: 'stock_moves#kardex'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock_move.rb
class StockMove
    include Mongoid::Document
    include Mongoid::Timestamps
    field :product_name, type: String
    field :product_id, type: Integer
    field :date, type: Time
    field :move_description, type: String
    field :uom_name, type: String
    field :quantity, type: Float
    field :product_cost, type: Float
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stock_moves_controller.rb
class StockMovesController < ApplicationController
  before_action :set_stock_move, only: [:show, :edit, :update, :destroy]
  before_action :set_stock_moves_by_product, only: [:kardex]
  # GET /stock_moves
  # GET /stock_moves.json
  def index
    @stock_moves = StockMove.all.sort({ date: 1})
  end

  # GET /stock_moves/1
  # GET /stock_moves/1.json
  def show
  end

  # GET /stock_moves/new
  def new
    @stock_move = StockMove.new
  end

  # GET /stock_moves/1/edit
  def edit
  end

  # GET /stock_moves/kardex/:product_id
  def kardex
    render json: @stock_moves_by_product
  end

  # POST /stock_moves
  # POST /stock_moves.json
  def create
    @stock_move = StockMove.new(stock_move_params)

    respond_to do |format|
      if @stock_move.save
        format.html { redirect_to @stock_move, notice: 'Stock move was successfully created.' }
        format.json { render :show, status: :created, location: @stock_move }
      else
        format.html { render :new }
        format.json { render json: @stock_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_moves/1
  # PATCH/PUT /stock_moves/1.json
  def update
    respond_to do |format|
      if @stock_move.update(stock_move_params)
        format.html { redirect_to @stock_move, notice: 'Stock move was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_move }
      else
        format.html { render :edit }
        format.json { render json: @stock_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_moves/1
  # DELETE /stock_moves/1.json
  def destroy
    @stock_move.destroy
    respond_to do |format|
      format.html { redirect_to stock_moves_url, notice: 'Stock move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_move
      @stock_move = StockMove.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_move_params
      params.require(:stock_move).permit(:product_name, :product_id, :date, :move_description, :uom_name, :quantity, :product_cost)
    end

    def set_stock_moves_by_product
      @stock_moves_by_product = StockMove.where(product_id: params[:product_id]).sort({ date: 1})
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_moves_helper.rb
module StockMovesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chiquitania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stock_moves/_form.html.erb
<%= form_with(model: stock_move, local: true) do |form| %>
  <% if stock_move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock_move.errors.count, "error") %> prohibited this stock_move from being saved:</h2>

      <ul>
        <% stock_move.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :move_description %>
    <%= form.text_field :move_description %>
  </div>

  <div class="field">
    <%= form.label :uom_name %>
    <%= form.text_field :uom_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :product_cost %>
    <%= form.text_field :product_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stock_moves/edit.html.erb
<h1>Editing Stock Move</h1>

<%= render 'form', stock_move: @stock_move %>

<%= link_to 'Show', @stock_move %> |
<%= link_to 'Back', stock_moves_path %>

app/views/stock_moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stock Moves</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product</th>
      <th>Date</th>
      <th>Move description</th>
      <th>Uom name</th>
      <th>Quantity</th>
      <th>Product cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stock_moves.each do |stock_move| %>
      <tr>
        <td><%= stock_move.product_name %></td>
        <td><%= stock_move.product_id %></td>
        <td><%= stock_move.date %></td>
        <td><%= stock_move.move_description %></td>
        <td><%= stock_move.uom_name %></td>
        <td><%= stock_move.quantity %></td>
        <td><%= stock_move.product_cost %></td>
        <td><%= link_to 'Show', stock_move %></td>
        <td><%= link_to 'Edit', edit_stock_move_path(stock_move) %></td>
        <td><%= link_to 'Destroy', stock_move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock Move', new_stock_move_path %>

app/views/stock_moves/new.html.erb
<h1>New Stock Move</h1>

<%= render 'form', stock_move: @stock_move %>

<%= link_to 'Back', stock_moves_path %>

app/views/stock_moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @stock_move.product_name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @stock_move.product_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stock_move.date %>
</p>

<p>
  <strong>Move description:</strong>
  <%= @stock_move.move_description %>
</p>

<p>
  <strong>Uom name:</strong>
  <%= @stock_move.uom_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @stock_move.quantity %>
</p>

<p>
  <strong>Product cost:</strong>
  <%= @stock_move.product_cost %>
</p>

<%= link_to 'Edit', edit_stock_move_path(@stock_move) %> |
<%= link_to 'Back', stock_moves_path %>